import type { Metadata } from "next";
import { dbConfig } from "@/utils/dbConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body>
        <main className=" min-h-[100vh] p-2 w-full flex justify-center ">
          <div className="w-full  lg:w-[1200px] ">
            <div className="p-2 border rounded-md h-full">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
