import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbConfig";
import Provider from "./static/Provider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./static/ThemeProvider";
import ReduxProvider from "./global/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Provider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>

            <Toaster />
          </Provider>
        </body>
      </html>
    </ReduxProvider>
  );
}
